palette = "cutiepro"
add_newline = true
follow_symlinks = true
format = """
(\
([î‚¶](strawberry)$os$username$hostname$localip$netns[î‚°](strawberry))\
)\
(\
([îƒ—](cherry_blossom)$directory[î‚°](cherry_blossom))\
)\
(\
([îƒ—](honeycomb)$vcsh[î‚°](honeycomb))\
([îƒ—](honeycomb)$git_branch$git_commit$git_status$git_metrics$git_state[î‚°](honeycomb))\
([îƒ—](honeycomb)$hg_branch[î‚°](honeycomb))\
([îƒ—](honeycomb)$fossil_branch$fossil_metrics[î‚°](honeycomb))\
([îƒ—](honeycomb)$pijul_channel[î‚°](honeycomb))\
)\
(\
([îƒ—](sour_apple)$bun[î‚°](sour_apple))\
([îƒ—](sour_apple)$deno[î‚°](sour_apple))\
([îƒ—](sour_apple)$nodejs[î‚°](sour_apple))\
([îƒ—](sour_apple)$purescript[î‚°](sour_apple))\
([îƒ—](sour_apple)$c[î‚°](sour_apple))\
([îƒ—](sour_apple)$cpp[î‚°](sour_apple))\
([îƒ—](sour_apple)$cmake[î‚°](sour_apple))\
([îƒ—](sour_apple)$cobol[î‚°](sour_apple))\
([îƒ—](sour_apple)$crystal[î‚°](sour_apple))\
([îƒ—](sour_apple)$daml[î‚°](sour_apple))\
([îƒ—](sour_apple)$dart[î‚°](sour_apple))\
([îƒ—](sour_apple)$dotnet[î‚°](sour_apple))\
([îƒ—](sour_apple)$elixir[î‚°](sour_apple))\
([îƒ—](sour_apple)$elm[î‚°](sour_apple))\
([îƒ—](sour_apple)$fennel[î‚°](sour_apple))\
([îƒ—](sour_apple)$gleam[î‚°](sour_apple))\
([îƒ—](sour_apple)$golang[î‚°](sour_apple))\
([îƒ—](sour_apple)$buf[î‚°](sour_apple))\
([îƒ—](sour_apple)$helm[î‚°](sour_apple))\
([îƒ—](sour_apple)$opa[î‚°](sour_apple))\
([îƒ—](sour_apple)$haskell[î‚°](sour_apple))\
([îƒ—](sour_apple)$haxe[î‚°](sour_apple))\
([îƒ—](sour_apple)$java[î‚°](sour_apple))\
([îƒ—](sour_apple)$kotlin[î‚°](sour_apple))\
([îƒ—](sour_apple)$scala[î‚°](sour_apple))\
([îƒ—](sour_apple)$gradle[î‚°](sour_apple))\
([îƒ—](sour_apple)$julia[î‚°](sour_apple))\
([îƒ—](sour_apple)$lua[î‚°](sour_apple))\
([îƒ—](sour_apple)$mojo[î‚°](sour_apple))\
([îƒ—](sour_apple)$nim[î‚°](sour_apple))\
([îƒ—](sour_apple)$ocaml[î‚°](sour_apple))\
([îƒ—](sour_apple)$odin[î‚°](sour_apple))\
([îƒ—](sour_apple)$perl[î‚°](sour_apple))\
([îƒ—](sour_apple)$php[î‚°](sour_apple))\
([îƒ—](sour_apple)$python[î‚°](sour_apple))\
([îƒ—](sour_apple)$quarto[î‚°](sour_apple))\
([îƒ—](sour_apple)$raku[î‚°](sour_apple))\
([îƒ—](sour_apple)$rlang[î‚°](sour_apple))\
([îƒ—](sour_apple)$red[î‚°](sour_apple))\
([îƒ—](sour_apple)$ruby[î‚°](sour_apple))\
([îƒ—](sour_apple)$vagrant[î‚°](sour_apple))\
([îƒ—](sour_apple)$rust[î‚°](sour_apple))\
([îƒ—](sour_apple)$solidity[î‚°](sour_apple))\
([îƒ—](sour_apple)$swift[î‚°](sour_apple))\
([îƒ—](sour_apple)$typst[î‚°](sour_apple))\
([îƒ—](sour_apple)$vlang[î‚°](sour_apple))\
([îƒ—](sour_apple)$zig[î‚°](sour_apple))\
)\
(\
([îƒ—](peacock)$package[î‚°](peacock))\
)\
(\
([îƒ—](sky)$singularity[î‚°](sky))\
([îƒ—](sky)$kubernetes[î‚°](sky))\
([îƒ—](sky)$docker_context[î‚°](sky))\
([îƒ—](sky)$container[î‚°](sky))\
([îƒ—](sky)$guix_shell[î‚°](sky))\
([îƒ—](sky)$nix_shell[î‚°](sky))\
([îƒ—](sky)$aws[î‚°](sky))\
([îƒ—](sky)$azure[î‚°](sky))\
([îƒ—](sky)$gcloud[î‚°](sky))\
([îƒ—](sky)$openstack[î‚°](sky))\
([îƒ—](sky)$nats[î‚°](sky))\
([îƒ—](sky)$pulumi[î‚°](sky))\
([îƒ—](sky)$terraform[î‚°](sky))\
([îƒ—](sky)$conda[î‚°](sky))\
([îƒ—](sky)$pixi[î‚°](sky))\
([îƒ—](sky)$meson[î‚°](sky))\
([îƒ—](sky)$spack[î‚°](sky))\
([îƒ—](sky)$direnv[î‚°](sky))\
([îƒ—](sky)$mise[î‚°](sky))\
)\
$fill\
(\
([î‚¶](salmon)$status[î‚´](salmon) )\
([î‚¶](princess)$battery[î‚´](princess) )\
([î‚¶](creamsicle)$memory_usage[î‚´](creamsicle) )\
([î‚¶](princess)$sudo[î‚´](princess) )\
([î‚¶](creamsicle)$shell[î‚´](creamsicle) )\
([î‚¶](creamsicle)$jobs[î‚´](creamsicle) )\
([î‚¶](blueberry)$cmd_duration[î‚´](blueberry) )\
([î‚¶](lilac)$time[î‚´](lilac))\
)\
$line_break\
$shlvl$character
"""

[os]
disabled = false
style = "bg:strawberry fg:raven"
format = "[$symbol]($style)"

[os.symbols]
Alpaquita = "îª¢ "
Alpine = "ïŒ€ "
AlmaLinux = "ïŒ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
Artix = "ïŒŸ "
CachyOS = "ïŒƒ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ó°›“ "
Gentoo = "ïŒ "
HardenedBSD = "ó°Œ "
Illumos = "ó°ˆ¸ "
Kali = "ïŒ§ "
Linux = "ïŒš "
Mabox = "î¬© "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
Nobara = "ï€ "
OpenBSD = "ó°ˆº "
openSUSE = "ïŒ” "
OracleLinux = "ó°Œ· "
Pop = "ïŒª "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
RockyLinux = "ïŒ« "
Redox = "ó°€˜ "
Solus = "ó° ³ "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Void = "ïŒ® "
Windows = "ó°² "

[username]
disabled = false
style_user = "bg:strawberry fg:raven"
style_root = "bg:strawberry fg:raven bold italic"
format = "[îƒ—î‚°]($style)[ ï€‡ $user ]($style)"
# format = "[î‚± ï€‡ $user ]($style)"
# show_always = false
show_always = true

[hostname]
disabled = false
ssh_symbol = "î¬ "
style = "bg:strawberry fg:raven"
format = "[îƒ—î‚°]($style)[ $ssh_symbol$hostname ]($style)"
ssh_only = true
# ssh_only = false
trim_at = ""

[localip]
disabled = false
style = "bg:strawberry fg:raven"
format = '[\($localipv4\) ]($style)'
ssh_only = true
# ssh_only = false

[netns]
disabled = false
symbol = "îª‹ "
style = "bg:strawberry fg:raven"
format = '[îƒ—î‚°]($style)[ $symbol \[$name\] ]($style)'

[directory]
disabled = false
truncation_symbol = "â€¦/"
read_only = "ó°Œ¾"
home_symbol = "ï€• "
style = "bg:cherry_blossom fg:raven bold"
read_only_style = "bg:cherry_blossom fg:raven bold"
before_repo_root_style = "bg:cherry_blossom fg:soil"
repo_root_style = "bg:cherry_blossom fg:raven bold"
format = "[ $path( $read_only) ]($style)"
repo_root_format = "[ ïˆ $repo_root]($repo_root_style)[$path ]($style)([$read_only]($read_only_style))"
use_os_path_sep = false
truncation_length = 5
# path_sep = " î‚± "

[directory.substitutions]
# '/' = ' î‚± '

[vcsh]
disabled = false
symbol = "ó°³ "
style = "bg:honeycomb fg:raven"
format = "[ $symbol$repo ]($style)"

[git_branch]
disabled = false
symbol = "î‚ "
truncation_symbol = "â€¦"
style = "bg:honeycomb fg:raven"
format = "[ $symbol$branch(:$remote_branch) ]($style)"
always_show_remote = false
only_attached = false
# truncation_length = 20

[git_commit]
disabled = false
tag_symbol = "ï’ "
style = "bg:honeycomb fg:raven"
format = '[\($hash( $tag)\) ]($style)'
tag_disabled = false
only_detached = true
# only_detached = false
commit_hash_length = 7
tag_max_candidates = 0  # exact matches only

[git_status]
disabled = false
style = "bg:honeycomb fg:raven"
format = "[($ahead_behind )(â”Š $conflicted$deleted$renamed$modified$typechanged$stashed$staged$untracked)]($style)"
up_to_date = "ğŸ—¸"
ahead = "â†‘${count}"
behind = "â†“${count}"
diverged = "â†‘${ahead_count} â†“${behind_count}"
conflicted = "â‰ ${count} "
untracked = "?${count} "
stashed = "\\$${count} "
modified = "!${count} "
staged = "+${count} "
renamed = "Â»${count} "
deleted = "âˆ’${count} "
typechanged = "â‡„ "
ignore_submodules = false
use_git_executable = false
# windows_starship = '/mnt/c/...'

[git_metrics]
disabled = true
# disabled = false
added_style = "bg:honeycomb fg:raven"
deleted_style = "bg:honeycomb fg:raven"
format = '([\((+$added)( âˆ’$deleted)\) ]($added_style))'
only_nonzero_diffs = true
ignore_submodules = false

[git_state]
disabled = false
style = "bg:honeycomb fg:raven"
format = "[$state( $progress_current/$progress_total) ]($style)"
rebase = "ó°‘ "
merge = "ó°½œ "
revert = "ó°Œ¥ "
cherry_pick = "îŠ› "
bisect = "î«¨ "
am = "ó°¶ˆ "
am_or_rebase = "ó°¶ˆ ó°œ¥ ó°‘ "

[hg_branch]
disabled = false
symbol = "ï˜ "
style = "bg:honeycomb fg:raven"
format = "[ $symbol$branch(:$topic) ]($style)"
truncation_symbol = "â€¦"
# truncation_length = 20

[fossil_branch]
disabled = false
symbol = "î‚ "
style = "bg:honeycomb fg:raven"
format = "[ $symbol$branch ]($style)"
truncation_symbol = "â€¦"
# truncation_length = 20

[fossil_metrics]
disabled = false
added_style = "bg:honeycomb fg:raven"
deleted_style = "bg:honeycomb fg:raven"
format = '[\((+$added)( âˆ’$deleted)\) ]($added_style)'
only_nonzero_diffs = true

[pijul_channel]
disabled = false
symbol = "î‚ "
style = "bg:honeycomb fg:raven"
format = "[ $symbol$channel ]($style)"
truncation_symbol = "â€¦"
# truncation_length = 20

[bun]
disabled = false
symbol = "î¯ "
style = "bg:sour_apple fg:raven"
format = "[ $symbol($version) ]($style)"

[deno]
disabled = false
symbol = "îŸ€ "
style = "bg:sour_apple fg:raven"
format = "[ $symbol($version) ]($style)"

[nodejs]
disabled = false
symbol = "îœ˜ "
style = "bg:sour_apple fg:raven"
format = "[ $symbol($version) ]($style)"

[purescript]
disabled = false
symbol = "î˜° "
style = "bg:sour_apple fg:raven"
format = "[ $symbol($version) ]($style)"

[c]
disabled = false
symbol = "î˜ "
style = "bg:sour_apple fg:raven"
format = "[ $symbol($version(-$name)) ]($style)"

[cpp]
disabled = false
symbol = "î˜ "
style = "bg:sour_apple fg:raven"
format = "[ $symbol($version(-$name)) ]($style)"

[cmake]
disabled = false
symbol = "î” "
style = "bg:sour_apple fg:raven"
format = "[ $symbol($version) ]($style)"

[cobol]
disabled = false
symbol = "âš™ "
style = "bg:sour_apple fg:raven"
format = "[ $symbol($version) ]($style)"

[crystal]
disabled = false
symbol = "î˜¯ "
style = "bg:sour_apple fg:raven"
format = "[ $symbol($version) ]($style)"

[daml]
disabled = false
style = "bg:sour_apple fg:raven"
format = "[ $symbol($version) ]($style)"

[dart]
disabled = false
symbol = "î˜ "
style = "bg:sour_apple fg:raven"
format = "[ $symbol($version) ]($style)"

[dotnet]
disabled = false
symbol = "î¿ "
style = "bg:sour_apple fg:raven"
format = "[ $symbol($version)(ó°£‰ $ftm) ]($style)"

[elixir]
disabled = false
symbol = "î˜­ "
style = "bg:sour_apple fg:raven"
format = '[ $symbol($version (\(OTP $otp_version\))) ]($style)'

[elm]
disabled = false
symbol = "î˜¬ "
style = "bg:sour_apple fg:raven"
format = "[ $symbol($version) ]($style)"

[fennel]
disabled = false
symbol = "îš¯ "
style = "bg:sour_apple fg:raven"
format = "[ $symbol($version) ]($style)"

[gleam]
disabled = false
symbol = "ï€… "
style = "bg:sour_apple fg:raven"
format = "[ $symbol($version) ]($style)"

[golang]
disabled = false
symbol = "î˜§ "
style = "bg:sour_apple fg:raven"
format = "[ $symbol($version) ]($style)"

[buf]
disabled = false
symbol = "ï’ "
style = "bg:sour_apple fg:raven"
format = "[ $symbol($version) ]($style)"

[helm]
disabled = false
symbol = "îŸ» "
style = "bg:sour_apple fg:raven"
format = "[ $symbol($version) ]($style)"

[opa]
disabled = false
symbol = "î¾„ "
style = "bg:sour_apple fg:raven"
format = "[ $symbol($version) ]($style)"

[haskell]
disabled = false
symbol = "î· "
style = "bg:sour_apple fg:raven"
format = "[ $symbol($version) ]($style)"

[haxe]
disabled = false
symbol = "î™¦ "
style = "bg:sour_apple fg:raven"
format = "[ $symbol($version) ]($style)"

[java]
disabled = false
symbol = "î‰– "
style = "bg:sour_apple fg:raven"
format = "[ $symbol($version) ]($style)"

[kotlin]
disabled = false
symbol = "î˜´ "
style = "bg:sour_apple fg:raven"
format = "[ $symbol($version) ]($style)"

[scala]
disabled = false
symbol = "îœ· "
style = "bg:sour_apple fg:raven"
format = "[ $symbol($version) ]($style)"

[gradle]
disabled = false
symbol = "î™  "
style = "bg:sour_apple fg:raven"
format = "[ $symbol($version) ]($style)"

[julia]
disabled = false
symbol = "î˜¤ "
style = "bg:sour_apple fg:raven"
format = "[ $symbol($version) ]($style)"

[lua]
disabled = false
symbol = "î˜  "
style = "bg:sour_apple fg:raven"
format = "[ $symbol($version) ]($style)"

[mojo]
disabled = false
symbol = "ï’ "
style = "bg:sour_apple fg:raven"
format = "[ $symbol($version) ]($style)"

[nim]
disabled = false
symbol = "ó°†¥ "
style = "bg:sour_apple fg:raven"
format = "[ $symbol($version) ]($style)"

[ocaml]
disabled = false
symbol = "î¡ "
style = "bg:sour_apple fg:raven"
format = '[ $symbol($version) (\($switch_indicator$switch_name\) )]($style)'

[odin]
disabled = false
style = "bg:sour_apple fg:raven"
format = "[ $symbol($version) ]($style)"

[perl]
disabled = false
symbol = "î™¾ "
style = "bg:sour_apple fg:raven"
format = "[ $symbol($version) ]($style)"

[php]
disabled = false
symbol = "î˜ˆ "
style = "bg:sour_apple fg:raven"
format = "[ $symbol($version) ]($style)"

[python]
disabled = false
symbol = "îˆµ "
style = "bg:sour_apple fg:raven"
format = '[ $symbol($pyenv_prefix) ($version )(\($virtualenv\) )]($style)'
pyenv_version_name = false
# pyenv_version_name = true

[quarto]
disabled = false
style = "bg:sour_apple fg:raven"
format = "[ $symbol($version) ]($style)"

[raku]
disabled = false
symbol = "îŠ "
style = "bg:sour_apple fg:raven"
format = "[ $symbol($version(-$vm_version)) ]($style)"

[rlang]
disabled = false
symbol = "ó°Ÿ” "
style = "bg:sour_apple fg:raven"
format = "[ $symbol($version) ]($style)"

[red]
disabled = false
style = "bg:sour_apple fg:raven"
format = "[ $symbol($version) ]($style)"

[ruby]
disabled = false
symbol = "î‘ "
style = "bg:sour_apple fg:raven"
format = "[ $symbol($version) ]($style)"

[vagrant]
disabled = false
style = "bg:sour_apple fg:raven"
format = "[ $symbol($version) ]($style)"

[rust]
disabled = false
symbol = "î¨ "
style = "bg:sour_apple fg:raven"
format = "[ $symbol($version) ]($style)"

[solidity]
disabled = false
style = "bg:sour_apple fg:raven"
format = "[ $symbol($version) ]($style)"

[swift]
disabled = false
symbol = "î• "
style = "bg:sour_apple fg:raven"
format = "[ $symbol($version) ]($style)"

[typst]
disabled = false
style = "bg:sour_apple fg:raven"
format = "[ $symbol($version) ]($style)"

[vlang]
disabled = false
style = "bg:sour_apple fg:raven"
format = "[ $symbol($version) ]($style)"

[zig]
disabled = false
symbol = "îš© "
style = "bg:sour_apple fg:raven"
format = "[ $symbol($version) ]($style)"

[package]
disabled = false
symbol = "ï’‡ "
style = "bg:peacock fg:raven"
format = "[ $symbol($version) ]($style)"
display_private = true

[singularity]
disabled = false
symbol = "î¬© "
style = "bg:sky fg:raven"
format = '[ $symbol\[$env\] ]($style)'

[kubernetes]
disabled = false
symbol = "î  "
style = "bg:sky fg:raven"
format = '[ $symbol$context(\($namespace\)) ]($style)'

[docker_context]
disabled = false
symbol = "ïŒˆ "
style = "bg:sky fg:raven"
format = "[ $symbol$context ]($style)"
only_with_files = true

[container]
disabled = false
symbol = "î‰ "
style = "bg:sky fg:raven"
format = '[ $symbol \[$name\] ]($style)'

[guix_shell]
disabled = false
symbol = "ïŒ¥ "
style = "bg:sky fg:raven"
format = "[ $symbol]($style)"

[nix_shell]
disabled = false
symbol = "ïŒ“ "
style = "bg:sky fg:raven"
format = "[ $symbol$state ]($style)"
# heuristic = true
heuristic = false

[aws]
disabled = false
symbol = "î­ "
style = "bg:sky fg:raven"
format = '[ $symbol($profile)( \($region\))( \[$duration\]) ]($style)'

[azure]
disabled = false
symbol = "î¯˜ "
style = "bg:sky fg:raven"
format = "[ $symbol($subscription) ]($style)"

[gcloud]
disabled = false
symbol = "ó±‡¶ "
style = "bg:sky fg:raven"
format = '[ $symbol$account(@$domain)( \($region\)) ]($style)'

[openstack]
disabled = false
symbol = "î¡– "
style = "bg:sky fg:raven"
format = '[ $symbol$cloud( \($project\)) ]($style)'

[nats]
disabled = false
symbol = "ïƒ  "
style = "bg:sky fg:raven"
format = "[ $symbol$name ]($style)"

[pulumi]
disabled = false
symbol = "î¡³ "
style = "bg:sky fg:raven"
format = "[ $symbol($username@)$stack ]($style)"

[terraform]
disabled = false
symbol = "î¢½ "
style = "bg:sky fg:raven"
format = "[ $symbol$workspace ]($style)"

[conda]
disabled = false
symbol = "ï„Œ "
style = "bg:sky fg:raven"
format = "[ $symbol$environment ]($style)"

[pixi]
disabled = false
symbol = "ó°— "
style = "bg:sky fg:raven"
format = '[ $symbol($version)( \($environment\)) ]($style)'

[meson]
disabled = false
symbol = "ó°”· "
style = "bg:sky fg:raven"
format = "[ $symbol$project ]($style)"

[spack]
disabled = false
symbol = "î¢ª "
style = "bg:sky fg:raven"
format = "[ $symbol$environment ]($style)"

[direnv]
disabled = false
style = "bg:sky fg:raven"
format = "[ $symbol$loaded/$allowed ]($style)"

[mise]
disabled = false
style = "bg:sky fg:raven"
format = "[ $symbol$health ]($style)"

[fill]
symbol = " "

[status]
disabled = false
symbol = "îª‡ "
# success_symbol = "îª² "
not_executable_symbol = "îª½ "
not_found_symbol = "î©­ "
sigint_symbol = "î€‰"
signal_symbol = "î€Š"
style = "bg:salmon fg:raven bold"
format = "[$symbol$status]($style)"
map_symbol = true

[battery]
disabled = true
format = "[$symbol$percentage]($style)"

[[battery.display]]
threshold = 20
# threshold = 100
style = "bg:princess fg:raven bold"

# [[battery.display]]
# threshold = 100
# style = "bg:creamsicle fg:raven"

[memory_usage]
disabled = true
# disabled = false
symbol = "ó°› "
style = "bg:creamsicle fg:raven"
format = "[$symbol$ram( | $swap)]($style)"
threshold = 80
# threshold = -1

[sudo]
disabled = false
symbol = "î¼ "
style = "bg:princess fg:raven"
format = "[$symbol]($style)"

[shell]
disabled = true
# disabled = false
style = "bg:creamsicle fg:raven"
format = "[îš‘$indicator ]($style)"

[jobs]
disabled = false
symbol = "ó°«¢ "
style = "bg:creamsicle fg:raven"
format = "[$symbol$number]($style)"

[cmd_duration]
disabled = false
style = "bg:blueberry fg:raven"
format = "[ï‰“ $duration]($style)"
show_milliseconds = true
# min_time = 2_000
# min_time = 0
min_time = 1
show_notifications = false
# min_time_to_notify = 45_000
# notification_timeout = 5_000

[time]
disabled = false
style = "bg:lilac fg:raven"
format = "[ï€— $time]($style)"

[shlvl]
disabled = false
symbol = "â¥"
style = "chalk bold"
format = "[$symbol]($style)"
repeat = true
repeat_offset = 1
threshold = 0

[character]
disabled = false
success_symbol = "[â¥](cherry_blossom bold)"
error_symbol = "[â¥](cherry_blossom bold)"
vimcmd_symbol = "[â¥](cherry_blossom bold)"
vimcmd_replace_one_symbol = "[â¥](lilac bold)"
vimcmd_replace_symbol = "[â¥](lilac bold)"
vimcmd_visual_symbol = "[â¥](sky bold)"

[palettes.cutiepro]
blackboard = "#181716"
strawberry = "#f56e7f"
sour_apple = "#bec975"
honeycomb = "#e8d6a7"
lilac = "#caa2ca"
cherry_blossom = "#e5a1a3"
sky = "#a5b6ce"
elephant = "#88847f"
soil = "#73665b"
salmon = "#f58669"
goddess = "#a2caa0"
creamsicle = "#f7bb6c"
blueberry = "#9293ec"
princess = "#ef7dc0"
peacock = "#5dccc3"
chalk = "#d5d0c9"
cocoa = "#1f1e1b"
raven = "#0a0909"
metal = "#212225"
date = "#210f11"
film = "#2e2a27"
charcoal = "#313735"
asphalt = "#43403d"
sea = "#0f3f4e"
opium = "#978182"
sage = "#878972"
cloud = "#808387"
nectarine = "#f1d090"
lemon = "#ffef43"
