[alias]
bin = ["run", "--package", "cargo-bin", "--"]
bi = ["binstall"]
install-theymer = ["install", "--path", "."]
it = ["install-theymer"]
m = ["modules"]
u = ["upgrade"]
binstall = ["bin", "cargo-binstall"]
modules = ["bin", "cargo-modules"]
set-version = ["bin", "cargo-set-version"]
upgrade = ["bin", "cargo-upgrade"]

[build]
rustc-wrapper = "sccache"
