[alias]
bin = ["run", "--package", "cargo-bin", "--"]
install-they = ["install", "--path", "crates/theythemer"]
it = ["install-they"]
m = ["modules"]
u = ["upgrade"]
binstall = ["bin", "cargo-binstall"]
modules = ["bin", "cargo-modules"]
set-version = ["bin", "cargo-set-version"]
upgrade = ["bin", "cargo-upgrade"]

[build]
rustc-wrapper = "sccache"
